version: "2"

services:

  monica-migrate:
    image: monica
    depends_on:
      - db
    environment:
      - DB_HOST=db
    entrypoint: "/usr/local/bin/php artisan migrate"
    #entrypoint: "/usr/local/bin/php artisan monica:admin --email=test@test.com --force"

  app:
    image: monica
    depends_on:
      - db
      - mail
    environment:
      - APP_KEY=ChangeMeBy32KeyLengthOrGenerated
      - DB_HOST=db
      - MAIL_MAILER=smtp
      - MAIL_HOST=fake_mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=monica@etiennelb.com
      - MAIL_FROM_NAME="Some Name"
      - APP_EMAIL_NEW_USERS_NOTIFICATION=
      #- REQUIRES_SUBSCRIPTION=false
      #- APP_DISABLE_SIGNUP=true
    ports:
      - 8080:80
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  mail:
    container_name: fake_mail
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: homestead
      PMA_PASSWORD: secret
    restart: always
    ports:
      - 3000:80
    volumes:
      - /sessions

volumes:
  data:
  mysql: